version: '3.4'

services:
  prediction-webapp:
    image: ${DOCKER_REGISTRY-}prediction-webapp
    build:
      context: ../src/backend
      dockerfile: Cloud/DraftPrediction/Dockerfile
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
